post_install() {
	xdg-icon-resource install --context mimetypes --size 64 \
	/usr/share/gambas3/mime/application-x-gambasscript.png application-x-gambasscript
	xdg-icon-resource install --context mimetypes --size 64 \
	/usr/share/gambas3/mime/application-x-gambasserverpage.png application-x-gambasserverpage
	xdg-mime install /usr/share/gambas3/mime/application-x-gambasscript.xml
	xdg-mime install /usr/share/gambas3/mime/application-x-gambasserverpage.xml
	
	xdg-icon-resource install --context mimetypes --size 64 \
	/usr/share/gambas3/mime/application-x-gambas.png application-x-gambas3
	xdg-mime install /usr/share/gambas3/mime/application-x-gambas3.xml
}

pre_remove() {
	xdg-icon-resource uninstall --context mimetypes --size 64 application-x-gambasscript
	xdg-icon-resource uninstall --context mimetypes --size 64 application-x-gambasserverpage
	xdg-icon-resource uninstall --context mimetypes --size 64 application-x-gambas3
	xdg-mime uninstall /usr/share/gambas3/mime/application-x-gambasscript.xml
	xdg-mime uninstall /usr/share/gambas3/mime/application-x-gambasserverpage.xml
	xdg-mime uninstall /usr/share/gambas3/mime/application-x-gambas3.xml
}